### ISSUE TITLE
Add a static map to AddressDataExtension?

### ISSUE THREAD

**Issue by mak001** [dynamic/silverstripe-geocoder#17]
The old addressable module did this.

https://github.com/symbiote/silverstripe-addressable/blob/7eb2f81c66502093c82c293943f43de9154ad807/code/Addressable.php#L199-L216

**Comment by muskie9** [comment]
Let's bring this over. Was a nice feature.

**Comment by korthjp17** [comment]
Along with this, could we bring over https://github.com/symbiote/silverstripe-addressable/blob/master/code/Addressable.php#L173-L188 ?

This is nice for building the map in that template file so we can use this instead of including all of the pieces in the template.

**Comment by mak001** [comment]
The `getFullAddress()` method is already in.
