### ISSUE TITLE
BUG Latitude and Longitude are reversed when storing results

### ISSUE THREAD

**Issue by obj63mc** [dynamic/silverstripe-geocoder#64]
Currently with the latest version of this module, when addresses are geocoded from google, you are storing the Longitude into the Latitude, and the Latitude into the Longitude.

1. Add a new location, example - 7303 Marietta Ave, Saint Louis MO, 63143 US
2. When geocoded from google the result from the api is - 
        
        Array
        (
            [type] => Feature
            [geometry] => Array
                (
                    [type] => Point
                    [coordinates] => Array
                        (
                            [0] => -90.3170937
                            [1] => 38.6126069
                        )

                )

            [properties] => Array
                (
                    [providedBy] => google_maps
                    [streetNumber] => 7303
                    [streetName] => Marietta Avenue
                    [postalCode] => 63143
                    [locality] => Maplewood
                    [adminLevels] => Array
                        (
                            [1] => Array
                                (
                                    [name] => Missouri
                                    [code] => MO
                                    [level] => 1
                                )

                            [2] => Array
                                (
                                    [name] => St. Louis County
                                    [code] => St Louis County
                                    [level] => 2
                                )

                            [3] => Array
                                (
                                    [name] => Hadley Township
                                    [code] => Hadley Township
                                    [level] => 3
                                )

                        )

                    [country] => United States
                    [countryCode] => US
                )

            [bounds] => Array
                (
                    [south] => 38.6124418
                    [west] => -90.3172328
                    [north] => 38.6127996
                    [east] => -90.3169649
                )

        )'
3. You then store the results geometry->coordinates->0 into Latitude but that is actually the Longitude for the location and vice versa

**Expected behavior**
Simply need to reverse which you are storing. Update src/AddressDataExtension.php lines 305 and 306

**Comment by obj63mc** [comment]
Actually when looking at the code, there is a more proper way to get the Latitude/Longitude from geocoder using their default methods.  Will submit a PR for this.

**Comment by jsirish** [comment]
closed via #65
